services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file: apps/web/.env.docker
    ports:
      - "${WEB_PORT:-3000}:3000"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: apps/api/.env.docker
    ports:
      - "${API_PORT:-3333}:3333"
